# A sample Guardfile
# More info at https://github.com/guard/guard#readme

# if your project does not have a Guardfile
# you can create one by running: 'bundle exex guard init'

# start guard by running 'bundle exex guard'

guard :rspec, cmd: "bundle exec rspec" do
  require "guard/rspec/dsl"
  dsl = Guard::RSpec::Dsl.new(self)

  # RSpec files
  rspec = dsl.rspec
  watch(rspec.spec_helper) { rspec.spec_dir }
  watch(rspec.spec_support) { rspec.spec_dir }
  watch(rspec.spec_files)

  # Ruby files
  ruby = dsl.ruby
  dsl.watch_spec_files_for(ruby.lib_files)

  # watch the models/ and lib/ directory and their specs
  # actually the lib/ directory is already being watched
  # by the line above this comment, I just added it as an example
  #
  # to understand the following two lines,
  # you should learn about RegEx - regular expressions
  #
  watch(%r{^models/(.+)\.rb}) { |m| "spec/models/#{m[1]}_spec.rb" }
  watch(%r{^lib/(.+)\.rb})    { |m| "spec/lib/#{m[1]}_spec.rb" }
end
